# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pull request checks

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 3.14 has a build issue related to the resolved Py03 version.
        # Py03 itself supports 3.14, 3.14t since 0.26.0: https://github.com/PyO3/pyo3/releases/tag/v0.26.0
        # python-version: [3.13, 3.14.0-rc.3]
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv wheel    
        pipenv install --system --dev
    #- name: Lint with flake8
    #  run: |
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
